apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-scratch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-simulator
spec:
  schedule: "*/10 * * * *"
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 172800
      activeDeadlineSeconds: 300
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: backup-simulator
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app: backup-simulator
                    topologyKey: kubernetes.io/hostname
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
          containers:
            - name: backup
              image: busybox:1.36
              command:
                - /bin/sh
                - -c
                - |
                  echo "[$(date)] Starting backup simulation"
                  echo "[$(date)] Writing test data to volume..."
                  for i in $(seq 1 3); do
                    echo "[$(date)] Iteration $i" >> /backup/log.txt
                    dd if=/dev/urandom of=/backup/chunk_$i.dat bs=1K count=10 2>/dev/null
                    sleep 2
                  done
                  echo "[$(date)] Backup simulation complete"
                  ls -la /backup/
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 64Mi
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: backup-scratch
